# docker-compose.yml
version: "2"
services:
  webapp_envios_dev:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "80"
    # volumes:
    # - /Users/kbs/git/peladonerd/varios/1/www:/usr/share/nginx/html:ro
    # - //d/storeDocker/html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=envios.apps.com.pe,www.envios.apps.com.pe
      - LETSENCRYPT_HOST=envios.apps.com.pe,www.envios.apps.com.pe
      - LETSENCRYPT_EMAIL=miguekos1233@gmail.com
networks:
  default:
    external:
      name: nginx-proxy_default
